version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    ports:
    - '9092:9092'
    environment:
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  minio:
    image: 'minio/minio'
    ports:
    - '9000:9000'
    command: ['server', '/data']
  input-listener:
    image: input-listener
    volumes:
    - ./input-listener:/app
    - ./logs/input-listener:/var/log